name: build_tcl
description: 'Build Tcl library'

inputs:
  cmake_generator:
    description: 'Makefile generator used by CMake'
    required: true
    default: 'Unix Makefiles'

runs:
  using: "composite"

  steps:

    - name: Tcl - Unix
      if: inputs.cmake_generator == 'Unix Makefiles'
      run: |
        echo '### download ###'
        cd ~
        git clone https://github.com/tcltk/tcl.git
        echo '### configure ###'
        cd tcl/unix/
        ./configure --enable-64bit
        echo '### compile ###'
        make -j 8
        echo '### install ###'
        sudo make install
        echo '### include dir ###'
        cd /usr/local/include
        pwd
        ls -d */
        ls -c -ltd -- *tcl*
        echo '### lib dir ###'
        cd /usr/local/lib
        pwd
        ls -d */
        ls -c -ltd -- *tcl*
      shell: bash
    
    - name: Tcl - MinGW
      if: inputs.cmake_generator == 'MinGW Makefiles'
      run: |
        echo '### download ###'
        cd ~
        git clone https://github.com/tcltk/tcl.git
        echo '### configure ###'
        cd tcl/win/
        ./configure --enable-64bit
        echo '### compile ###'
        make -j 8
        echo '### install ###'
        make install
        echo '### include dir ###'
        cd /mingw64/include/
        pwd
        ls -d */
        ls -c -ltd -- *tcl*
        echo '### lib dir ###'
        cd /mingw64/lib/
        pwd
        ls -d */
        ls -c -ltd -- *tcl*
      shell: msys2 {0}

    - name: Tcl - VS17
      if: inputs.cmake_generator == 'Visual Studio 17 2022'
      run: |
        echo '### download ###'
        cd ~
        git clone https://github.com/tcltk/tcl.git
        cd tcl/win/
        echo '### modified rules.vc ###'
        (Get-Content -Path rules.vc) -Replace 'tsgx', 'sgx' | Set-Content -Path rules.vc
        echo '### run nmake ###'
        (get-command nmake).Path
        nmake -nologo -f makefile.vc release install
        echo '### install ###'
        mv -Path C:\Tcl -Destination '${{github.workspace}}/3rdparty/tcl-vc17-64-release'
        tree '${{github.workspace}}/3rdparty' /f /a
      shell: pwsh

#       echo '### modified buildall.vc.bat ###'
#       $buildallpath = (get-command VsDevCmd.bat).Path
#       echo $buildallpath
#       (get-command nmake).Path
#       (Get-Content -Path buildall.vc.bat) `
#       -Replace 'off', 'on' `
#       -Replace 'call \".*VsDevCmd.bat\"', "call '$buildallpath' amd64" `
#       -Replace 'set INSTALLDIR=.*Tcl', 'set INSTALLDIR=${{github.workspace}}/3rdparty/tcl-vc17-64' `
#       -Replace 'htmlhelp', 'install' `
#       -Replace 'shell', 'shell install' |
#       Set-Content -Path buildall.vc.bat
#       Get-Content -Path buildall.vc.bat

#       cd '${{github.workspace}}\3rdparty\tcl-vc17-64'
#       tree . /f /a
#       cp "./tclsh*.exe" ./tclsh.exe
#       tree . /f /a
        
#        echo '### nmake install ###'
#        nmake -nologo -f makefile.vc install

#       echo '### run buildall.vc.bat ###'
#       ./buildall.vc.bat
#       tree C:\Users\runneradmin\tcl\win\Release_AMD64_VC1934
#       nmake -nologo -f makefile.vc install 
#       tree '${{github.workspace}}\3rdparty\tcl-vc17-64'
#       tree C:\Tcl /f /a
#       echo '### nmake clean ###'
#       nmake -nologo -f makefile.vc clean OPTS=none
#       set INSTALLDIR="${{github.workspace}}/3rdparty/tcl-vc17-64"

#        echo '### modified makefile.vc ###'
#        (Get-Content -path makefile.vc) -Replace '-MD', '-MT' | Set-Content -Path makefile.vc
#        echo '### modified tclMain.c ###'
#        (Get-Content -path ../generic/tclMain.c) -Replace 'is.tty', '//is.tty' | Set-Content -Path ../generic/tclMain.c

#       echo '### install ###'
#       tree 'C:\Users\runneradmin\tcl\win\Release_AMD64_VC1934' /f /a
#       cp 'C:\Users\runneradmin\tcl\generic\tcl*.h'                    '${{github.workspace}}/dep/include/'
#       cp 'C:\Users\runneradmin\tcl\win\tcl*.h'                        '${{github.workspace}}/dep/include/'
#       cp 'C:\Users\runneradmin\tcl\win\Release_AMD64_VC1934\*.lib'    '${{github.workspace}}/dep/lib'
#       cp 'C:\Users\runneradmin\tcl\win\Release_AMD64_VC1934\*.dll'    '${{github.workspace}}/dep/lib'
#       tree '${{github.workspace}}/dep' /f /a
